version: "2.1"

services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    dns: 1.1.1.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SUBDOMAINS=domain1,domain2 
      - TOKEN=XXXX-XXXX-XXXX-XXXX-XXXX
      - LOG_FILE=true
    volumes:
      - /home/pi/duckdns/config:/config
    restart: unless-stopped
