version: "3"

services:
  mcserver:
    image: itzg/minecraft-server:java17
    container_name: mcserver
    ports:
      - 25565:25565
      - 8080:8080
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "4G"
      VERSION: "1.19"
      #PAPERBUILD: "82"
    volumes:
      - /path/to/server/data:/data
      - /path/to/server/backups:/backups
    tty: true
    stdin_open: true
    restart: unless-stopped
