version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "5390:53/tcp"
      - "5390:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'XXXX'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/pi/pihole/etc/pihole:/etc/pihole'
      - '/home/pi/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    networks:
      home:
        ipv4_address: 192.168.0.101
    restart: unless-stopped

networks:
  home:
    external: true
