version: "3"

services:

# GLUETUN
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetunnet
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9711:9711 # qbittorrent
      - 6881:6881 # qbittorrent
      - 6881:6881/udp #qbittorrent
      - 9721:9721 # prowlarr
      - 9722:8191 # flaresolverr
      - 9731:9731 # lidarr
    volumes:
      - /home/pi/gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
      - VPN_SERVICE_PROVIDER=XXXX
      - VPN_TYPE=XXXX
      - WIREGUARD_PRIVATE_KEY=XXXX
      - WIREGUARD_ADDRESSES=10.20.30.40/32
      - SERVER_HOSTNAMES=XX-XX-XX
    restart: unless-stopped

# QBITTORRENT
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=9711
    volumes:
      - /home/pi/qbittorrent/config:/config
      - /home/pi/qbittorrent/webui:/webui
      - /path/to/downloads:/downloads
    restart: unless-stopped

# PROWLARR
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/pi/prowlarr/config:/config
    restart: unless-stopped

# FLARESOLVERR
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Berlin
    restart: unless-stopped

# LIDARR
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/pi/lidarr/config:/config
      - /path/to/music:/music
      - /path/to/downloads:/downloads
    restart: unless-stopped
